import moment from 'moment'
import Head from 'next/head'
import { useState } from 'react'
import { scrapeEverything } from '../scrapers'
import styles from '../styles/Home.module.css'

type Props = {
  gigs: Array<Gig>
}

const Home = ({ gigs }: Props) => {
  const [showLutakko, setShowLutakko] = useState(true)
  const [showIlokivi, setShowIlokivi] = useState(true)
  const [showPoppari, setShowPoppari] = useState(true)

  return (
    <div className={styles.container}>
      <Head>
        <title>GigScraper</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <input
          type='checkbox'
          id='lutakkofilter'
          name='lutakkofilter'
          checked={showLutakko}
          onChange={(e) => setShowLutakko(e.target.checked)}
        />
        <label htmlFor='lutakkofilter'>Lutakko</label>
      </div>
      <div>
        <input
          type='checkbox'
          id='ilokivifilter'
          name='ilokivifilter'
          checked={showIlokivi}
          onChange={(e) => setShowIlokivi(e.target.checked)}
        />
        <label htmlFor='ilokivifilter'>Ilokivi</label>
      </div>
      <div>
        <input
          type='checkbox'
          id='popparifilter'
          name='popparifilter'
          checked={showPoppari}
          onChange={(e) => setShowPoppari(e.target.checked)}
        />
        <label htmlFor='popparifilter'>Poppari</label>
      </div>

      <table>
        <thead>
          <tr>
            <th>Esiintyjä</th>
            <th>Päivämäärä</th>
            <th>Hinta</th>
            <th>Paikka</th>
            <th>Loppuunmyyty</th>
            <th>Peruttu</th>
          </tr>
        </thead>
        <tbody>
          {gigs
            .filter(
              (x) =>
                (showLutakko && x.venue === 'Lutakko') ||
                (showIlokivi && x.venue === 'Ilokivi') ||
                (showPoppari && x.venue === 'Poppari')
            )
            .sort((a, b) => moment(a.date, 'DD.MM.YYYY').unix() - moment(b.date, 'DD.MM.YYYY').unix())
            .map((gig, i) => {
              return (
                <tr key={i}>
                  <td>
                    <a href={gig.link}>{gig.title}</a>
                  </td>
                  <td>{gig.date}</td>
                  <td>{gig.price}</td>
                  <td>{gig.venue}</td>
                  <td>{gig.soldOut && 'X'}</td>
                  <td>{gig.cancelled && 'X'}</td>
                </tr>
              )
            })}
        </tbody>
      </table>
    </div>
  )
}

export async function getStaticProps() {
  const gigs = await scrapeEverything()

  return {
    props: {
      gigs,
    },
    revalidate: 60 * 60 * 12, // 12 hours
  }
}

export default Home
